# Generated by Django 4.0.1 on 2022-01-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_resume_is_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
